const { test } = require('node:test')
const assert = require('node:assert/strict')
const { chromium } = require(process.env.CLIENT_QA_PLAYWRIGHT_MODULE || 'playwright')
const url = process.env.CLIENT_QA_URL || 'http://127.0.0.1:5173'
test('promotion entry opens real selection page and explicit own position controls catalog scope', async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CLIENT_QA_CHROME_EXECUTABLE })
  const errors = [], calls = []
  try {
    const page = await browser.newPage({ viewport: { width: 390, height: 844 } })
    page.on('pageerror', error => errors.push(error.message))
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()) })
    await page.route('**/api/v1/**', async route => {
      const request = route.request(), parsed = new URL(request.url())
      calls.push({ url: parsed.pathname + parsed.search, method: request.method(), authorization: request.headers().authorization })
      const data = parsed.pathname === '/api/v1/promotion-positions' ? { items: [{ id: 'p1', name: '合成验收本人位', scene: 'group', status: 'ENABLED', isDefault: true, canConvert: false, channels: [{ channel: 'JD', readiness: 'WAITING_CONFIGURATION' }] }] } : { items: [], capability: { allowed: false, reason: 'UNCONFIGURED' } }
      await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ code: 0, data }) })
    })
    await page.goto(url + '/#/pages/promotion/index')
    await page.locator('[data-test=promoter-materials-entry]').focus(); await page.keyboard.press('Enter')
    await page.getByText(/请登录后查看本人推广选品/).waitFor()
    assert.ok(page.url().includes('/pages/promotion/materials'))
    assert.equal(calls.length, 0)
    await page.evaluate(async () => {
      const vue = await import('/node_modules/@dcloudio/uni-h5-vue/dist/vue.runtime.esm.js')
      const { default: Page } = await import('/src/pages/promotion/materials.vue')
      const { promoterSessionKey } = await import('/src/features/promotion/session.ts')
      const host = document.createElement('div'); document.body.replaceChildren(host)
      window.qaSession = vue.ref('qa-own-material-identity')
      window.qaApp = vue.createApp(Page); window.qaApp.provide(promoterSessionKey, window.qaSession); window.qaApp.mount(host)
    })
    await page.locator('[data-test=position-choice]').waitFor()
    assert.equal(calls.length, 1); assert.equal(await page.locator('[data-test=position-confirm]').count(), 0)
    await page.locator('[data-test=position-choice]').focus(); await page.keyboard.press('Space')
    await page.getByText('投放场景：group（使用所选位的服务端场景）', { exact: true }).waitFor()
    await page.locator('uni-input[aria-label="城市编码"] input').fill('310100')
    await page.locator('uni-input[aria-label="业务范围"] input').fill('food')
    await page.locator('[data-test=position-confirm]').focus(); await page.keyboard.press('Enter')
    await page.getByText(/目录未配置/).waitFor()
    assert.equal(calls.length, 2)
    const query = new URL(calls[1].url, url).searchParams
    assert.equal(query.get('positionId'), 'p1'); assert.equal(query.get('scene'), 'group'); assert.equal(query.get('terminal'), 'H5')
    assert.equal(query.get('cityCode'), '310100'); assert.equal(query.get('business'), 'food')
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false)
    assert.equal(await page.locator('vite-error-overlay').count(), 0)
    if (process.env.CLIENT_QA_SCREENSHOT_DIR) await page.screenshot({ path: process.env.CLIENT_QA_SCREENSHOT_DIR + '/materials-page-390.png', fullPage: true })
    await page.locator('[data-test=materials-platform-TAOBAO]').click()
    await page.getByText(/当前接口没有淘宝推广位映射/).waitFor()
    assert.equal(await page.locator('[data-test=position-choice]').count(), 0)
    assert.equal(await page.locator('[data-test=position-confirm]').count(), 0); assert.equal(calls.length, 2)
    await page.evaluate(() => { window.qaSession.value = null })
    await page.getByText(/请登录后查看本人推广选品/).waitFor()
    assert.equal(await page.locator('.positions').count(), 0)
    await page.evaluate(() => window.qaApp.unmount())
    assert.deepEqual(errors, []); assert.ok(calls.every(call => call.method === 'GET' && call.authorization === 'Bearer qa-own-material-identity'))
  } finally { await browser.close() }
})
