import { afterEach, expect, it, vi } from 'vitest'
import { createCouponAPI, type Request } from '../src/features/coupons/api'
import { createCouponCatalog } from '../src/features/coupons/catalog'

const item = {
  id: 'coupon-1', platform: 'JD', claimMode: 'PLATFORM_ACTIVITY', actionLabel: '去平台领取 / 购买',
  title: '接口测试券', scope: 'ACTIVITY', scopeExternalId: '', scopeName: '', currency: 'CNY',
  discountMinor: 500, thresholdMinor: 2000, cityCode: '', cityName: '', business: '',
  ruleVersion: 'v1', updatedAt: '2026-09-18T00:00:00Z', expiresAt: '2030-01-01T00:00:00Z',
}
afterEach(() => vi.useRealTimers())
function harness() {
  const pending: { url: string; resolve: (value: Awaited<ReturnType<Request>>) => void }[] = []
  const request = vi.fn((url: string) => new Promise<Awaited<ReturnType<Request>>>(resolve => pending.push({ url, resolve })))
  const catalog = createCouponCatalog(createCouponAPI(request))
  const complete = (index: number, data: unknown, statusCode = 200) => pending[index].resolve({ statusCode, data: statusCode === 200 ? { code: 0, message: 'success', data } : data })
  const settle = async () => { for (let i = 0; i < 8; i++) await Promise.resolve() }
  return { catalog, pending, request, complete, settle }
}
it('loads a catalog and available cities without inventing fallback data', async () => {
  const { catalog, pending, complete, settle } = harness()
  catalog.selectPlatform('JD')
  expect(catalog.state.status).toBe('loading')
  expect(catalog.state.items).toEqual([])
  expect(pending.map(p => p.url)).toEqual(['/api/v1/coupon-cities?platform=JD', '/api/v1/coupons?platform=JD&limit=20'])
  complete(0, { items: [{ code: '110100', name: '北京' }] })
  complete(1, { items: [item], nextCursor: 'next-1' })
  await settle()
  expect(catalog.state.status).toBe('ready')
  expect(catalog.state.cities).toEqual([{ code: '110100', name: '北京' }])
  expect(catalog.state.items[0].id).toBe('coupon-1')
  expect(catalog.state.nextCursor).toBe('next-1')
})
it('invalidates list, detail, cursor and city requests immediately when changing platforms', async () => {
  const { catalog, complete, settle } = harness()
  catalog.selectPlatform('JD')
  complete(1, { items: [item], nextCursor: 'old-next' }); await settle()
  catalog.openDetail('coupon-1')
  catalog.selectPlatform('TAOBAO')
  expect(catalog.state.items).toEqual([])
  expect(catalog.state.nextCursor).toBe('')
  expect(catalog.state.detailId).toBe('')
  expect(catalog.state.detail).toBeNull()
  complete(0, { items: [{ code: 'old', name: '旧城市' }] })
  complete(2, item)
  complete(3, { items: [{ code: 'new', name: '新城市' }] })
  complete(4, { items: [{ ...item, id: 'new-coupon', platform: 'TB' }], nextCursor: '' })
  await settle()
  expect(catalog.state.cities[0].code).toBe('new')
  expect(catalog.state.items[0].id).toBe('new-coupon')
  expect(catalog.state.detail).toBeNull()
})
it.each([{ cityCode: '110100' }, { business: 'food' }])('ignores an older list response after changing context %j', async change => {
  const { catalog, complete, settle, pending } = harness()
  catalog.selectPlatform('JD')
  catalog.setContext({ platform: 'JD', ...change })
  expect(catalog.state.status).toBe('loading')
  expect(pending[2].url).toContain(change.cityCode ? 'cityCode=110100' : 'business=food')
  complete(1, { items: [item], nextCursor: 'old-next' })
  complete(2, { items: [], nextCursor: '' }); await settle()
  expect(catalog.state.items).toEqual([])
  expect(catalog.state.status).toBe('empty')
  expect(catalog.state.nextCursor).toBe('')
})
it('resets geographic and business context on a platform change', async () => {
  const { catalog } = harness()
  catalog.setContext({ platform: 'JD', cityCode: '110100', business: 'food' })
  catalog.selectPlatform('MEITUAN')
  expect(catalog.state.context).toEqual({ platform: 'MEITUAN', cityCode: '', business: '' })
})
it('preserves the current context when another consumer selects the same platform', () => {
  const { catalog, request } = harness()
  catalog.setContext({ platform: 'JD', cityCode: '110100', business: 'food' })
  catalog.selectPlatform('JD')
  expect(catalog.state.context.cityCode).toBe('110100')
  expect(request).toHaveBeenCalledTimes(2)
})
it('keeps nationwide catalog usable when initial city options fail', async () => {
  const { catalog, complete, settle } = harness()
  catalog.selectPlatform('JD')
  complete(0, { code: 'COUPONS_UNAVAILABLE' }, 503)
  complete(1, { items: [item], nextCursor: '' }); await settle()
  expect(catalog.state.citiesStatus).toBe('error')
  expect(catalog.state.context.cityCode).toBe('')
  expect(catalog.state.status).toBe('ready')
})
it('hides material and invalidates the active detail when the displayed coupon expires', async () => {
  const { catalog, complete, settle } = harness()
  catalog.selectPlatform('JD'); complete(1, { items: [item], nextCursor: 'next-1' }); await settle()
  catalog.openDetail('coupon-1'); complete(2, item); await settle()
  vi.useFakeTimers(); vi.setSystemTime('2030-01-01T00:00:00Z')
  catalog.pruneExpired()
  expect(catalog.state.items).toEqual([])
  expect(catalog.state.status).toBe('empty')
  expect(catalog.state.detail).toBeNull()
  expect(catalog.state.detailStatus).toBe('not-found')
  expect(catalog.state.expiredNotice).toContain('到期')
})
it('allows reading remaining pages when every currently displayed coupon has expired', async () => {
  const { catalog, complete, settle, pending } = harness()
  catalog.selectPlatform('JD'); complete(1, { items: [item], nextCursor: 'next-1' }); await settle()
  vi.useFakeTimers(); vi.setSystemTime('2030-01-01T00:00:00Z'); catalog.pruneExpired()
  catalog.loadMore()
  expect(pending[2].url).toContain('cursor=next-1')
  complete(2, { items: [{ ...item, id: 'next-coupon', expiresAt: '2031-01-01T00:00:00Z' }], nextCursor: '' }); await settle()
  expect(catalog.state.status).toBe('ready')
  expect(catalog.state.items[0].id).toBe('next-coupon')
})
it('uses freshly read detail metadata rather than an older list rule version', async () => {
  const { catalog, complete, settle } = harness()
  catalog.selectPlatform('JD'); complete(1, { items: [item], nextCursor: '' }); await settle()
  catalog.openDetail('coupon-1')
  complete(2, { ...item, ruleVersion: 'v2', discountMinor: 600, expiresAt: '2027-01-01T00:00:00Z' }); await settle()
  expect(catalog.state.items[0].ruleVersion).toBe('v2')
  expect(catalog.state.items[0].discountMinor).toBe(600)
})
it('invalidates a detail that expires earlier than the original list cache', async () => {
  const { catalog, complete, settle } = harness()
  catalog.selectPlatform('JD'); complete(1, { items: [item], nextCursor: '' }); await settle()
  catalog.openDetail('coupon-1'); complete(2, { ...item, expiresAt: '2027-01-01T00:00:00Z' }); await settle()
  vi.useFakeTimers(); vi.setSystemTime('2028-01-01T00:00:00Z'); catalog.pruneExpired()
  expect(catalog.state.detail).toBeNull()
  expect(catalog.state.detailStatus).toBe('not-found')
  expect(catalog.state.items).toEqual([])
})
it('guards concurrent pagination and retains the same cursor for an explicit retry', async () => {
  const { catalog, complete, settle, request, pending } = harness()
  catalog.selectPlatform('JD')
  complete(1, { items: [item], nextCursor: 'next-1' }); await settle()
  catalog.loadMore(); catalog.loadMore()
  expect(request).toHaveBeenCalledTimes(3)
  expect(catalog.state.loadingMore).toBe(true)
  complete(2, { code: 'COUPONS_UNAVAILABLE' }, 503); await settle()
  expect(catalog.state.items[0].id).toBe('coupon-1')
  expect(catalog.state.nextCursor).toBe('next-1')
  expect(catalog.state.pageError).not.toBe('')
  catalog.loadMore()
  expect(pending[3].url).toContain('cursor=next-1')
  complete(3, { items: [{ ...item, id: 'coupon-2' }], nextCursor: '' }); await settle()
  expect(catalog.state.items.map((i: typeof item) => i.id)).toEqual(['coupon-1', 'coupon-2'])
  expect(catalog.state.pageError).toBe('')
})
it('does not append duplicates or retain an infinite pagination cursor', async () => {
  const { catalog, complete, settle } = harness()
  catalog.selectPlatform('JD')
  complete(1, { items: [item], nextCursor: 'next-1' }); await settle()
  catalog.loadMore()
  complete(2, { items: [item], nextCursor: 'next-1' }); await settle()
  expect(catalog.state.items).toHaveLength(1)
  expect(catalog.state.pageError).not.toBe('')
})
it('does not reopen a closed detail or overwrite a newer detail with an old result', async () => {
  const { catalog, complete, settle } = harness()
  catalog.selectPlatform('JD')
  complete(1, { items: [item, { ...item, id: 'coupon-2' }], nextCursor: '' }); await settle()
  catalog.openDetail('coupon-1'); catalog.openDetail('coupon-2')
  complete(3, { ...item, id: 'coupon-2' }); complete(2, item); await settle()
  expect(catalog.state.detail?.id).toBe('coupon-2')
  catalog.openDetail('coupon-1'); catalog.closeDetail()
  complete(4, item); await settle()
  expect(catalog.state.detailId).toBe('')
  expect(catalog.state.detail).toBeNull()
})
it('clears a previous success before refresh and exposes a sanitized error', async () => {
  const { catalog, complete, settle } = harness()
  catalog.selectPlatform('JD')
  complete(1, { items: [item], nextCursor: '' }); await settle()
  catalog.refresh()
  expect(catalog.state.items).toEqual([])
  complete(2, { code: 'COUPONS_UNAVAILABLE', message: 'private DB detail' }, 503); await settle()
  expect(catalog.state.status).toBe('error')
  expect(catalog.state.error).not.toContain('private DB detail')
})
it('distinguishes expired detail and missing catalog route', async () => {
  const { catalog, complete, settle } = harness()
  catalog.selectPlatform('JD')
  complete(1, { items: [item], nextCursor: '' }); await settle()
  catalog.openDetail('coupon-1')
  complete(2, { code: 'COUPON_NOT_FOUND' }, 404); await settle()
  expect(catalog.state.detailStatus).toBe('not-found')
  catalog.refresh(); complete(3, '<html>not found</html>', 404); await settle()
  expect(catalog.state.status).toBe('unavailable')
})
it('removes a coupon from the cached list when a fresh detail confirms it no longer exists', async () => {
  const { catalog, complete, settle } = harness()
  catalog.selectPlatform('JD'); complete(1, { items: [item, { ...item, id: 'coupon-2' }], nextCursor: '' }); await settle()
  catalog.openDetail('coupon-1'); complete(2, { code: 'COUPON_NOT_FOUND' }, 404); await settle()
  expect(catalog.state.items.map(row => row.id)).toEqual(['coupon-2'])
  expect(catalog.state.detailStatus).toBe('not-found')
  expect(catalog.state.expiredNotice).toContain('已失效')
})
it.each(['PDD', 'ELEME'] as const)('keeps unopened %s empty without making requests', async platform => {
  const { catalog, request, settle } = harness()
  catalog.selectPlatform(platform); await settle()
  expect(catalog.state.status).toBe('unopened')
  expect(catalog.state.items).toEqual([])
  expect(request).not.toHaveBeenCalled()
})
